import Head from 'next/head'
import SimpleLayout from '../../src/gg/adaptor/web/assets/layouts/SimpleLayout'
import { CampaignCreateMain } from '../../src/gg/adaptor/web/views/campaigns/create/CampaignCreateMain'

export default function CampaignCreate() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SimpleLayout head={<h2>campaigns/create</h2>} main={<CampaignCreateMain />} />
    </>
  )
}
