import Head from 'next/head'
import { useRouter } from 'next/router'
import SimpleLayout from '../../../../src/gg/adaptor/web/assets/layouts/SimpleLayout'
import { useReportUC } from '../../../../src/gg/adaptor/web/hooks/useReportUC'

export default function Reports() {
  const router = useRouter()
  console.log(router)
  const reportUC = useReportUC()
  // const reportRes = reportUC.getReportById('site_10000', 'report_12')

  // if (reportRes.isLoading) return <>Loading...</>
  // const report = reportRes.data.data.report

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SimpleLayout head={'report.page'} main={<div>{/* <pre>{JSON.stringify(report, null, 2)}</pre> */}</div>} />
    </>
  )
}
