import Head from "next/head";
import Nav, { useNav, NavBtn } from "@/dtr/adaptor/web/features/nav";
import * as Layout from "@/dtr/adaptor/web/styles/layout.styled";

export default function About() {
  const list = Array.from({ length: 20 }, (_, idx) => idx);
  const navHook = useNav();
  return (
    <Layout.AppDocument>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.AppHeader>
        <NavBtn onClick={navHook.onOpenNav} />
        <h1>LOGO</h1>
        <h2>About Page</h2>
      </Layout.AppHeader>
      <Nav navHook={navHook} />
      <Layout.AppMain>
        <div
          style={{
            display: "flex",
            flexFlow: "column",
            gap: "12px",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {list.map((v) => (
            <div
              key={v}
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "50vw",
                height: "50vh",
                backgroundColor: "var(--brand_yellow_300)",
                border: "1px solid #000",
              }}
            >
              {v}
            </div>
          ))}
        </div>
      </Layout.AppMain>
      <Layout.AppFooter>footer</Layout.AppFooter>
    </Layout.AppDocument>
  );
}
