import Head from "next/head";
import SimpleLayout from "@/dtr/adaptor/web/assets/layouts/SimpleLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleLayout head={"index.page"} main={<TmplMain />} />
    </>
  );
}

const TmplMain = () => {
  return <div>index</div>;
};
