import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import * as Layout from "@/dtr/adaptor/web/styles/layout.styled";
import { AppNav, AppNavBtn } from "@/dtr/adaptor/web/components/nav/AppNav";
import { useNav } from "@/dtr/adaptor/web/hooks";

export default function Home() {
  const list = Array.from({ length: 20 }, (_, idx) => idx);
  const navHook = useNav();
  return (
    <Layout.AppDocument>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.AppHeader>
        <AppNavBtn handler={navHook.onOpen} />
      </Layout.AppHeader>
      <AppNav hook={navHook} />
      <Layout.AppMain>
        <div
          style={{
            display: "flex",
            flexFlow: "column",
            gap: "12px",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {list.map((v) => (
            <div
              key={v}
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "50vw",
                height: "50vh",
                background: "#fff",
              }}
            >
              {v}
            </div>
          ))}
        </div>
      </Layout.AppMain>
      <Layout.AppFooter>footer</Layout.AppFooter>
    </Layout.AppDocument>
  );
}
