import Head from "next/head";
import { useEffect, useState } from "react";
import SimpleLayout from "@/dtr/adaptor/web/assets/layouts/SimpleLayout";
import { SiteGetUseCase } from "@/dtr/application/useCases/Site.get.uc";
import { reqGetSites, reqGetUser } from "@/dtr/adaptor/api";
import * as UI from "@/dtr/adaptor/web/features/card";
import { CardBasic } from "@/dtr/adaptor/web/features/card";

export default function Sites() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleLayout head={"sites.page"} main={<TmplMain />} />
    </>
  );
}

const TmplMain = () => {
  const [uc, setUc] = useState(new SiteGetUseCase());
  useEffect(() => {
    const _uc = new SiteGetUseCase({
      userRes: reqGetUser({ user_id: "test-user" }),
      sitesRes: reqGetSites({ page_no: 1, page_size: 10 }),
    });
    setUc(_uc);
  }, []);
  console.log(uc);
  return (
    <UI.Cards>
      {uc.ready() &&
        uc.sitesDto.siteEntities.map((site) => (
          <CardBasic key={site.id} site={site} />
        ))}
    </UI.Cards>
  );
};
