import Head from "next/head";
import SimpleLayout from "@/gg/adaptor/web/assets/layouts/SimpleLayout";
import { SitesMain } from "@/gg/adaptor/web/views/sites/SitesMain";

export default function Sites() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleLayout head={"sites.page"} main={<SitesMain />} />
    </>
  );
}
